# +++ TRAVIS-FILE for https://github.com/h-da/geli +++

# required for chrome to install
dist: trusty
# required for e2e tests to complete succesfully (page crash???)
sudo: required
language: node_js
node_js:
  - "7.9.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      # manually update dependencies for chrome
      - libfontconfig1
      - libstdc++6
      - lsb-base
      # used for frontend e2e tests
      - google-chrome-stable

services:
  - mongodb
  - docker

branches:
  only:
    - develop
    - master
    # This matches tags wit a format of v{MAJOR}.{MINOR}.{FIX} were major minor and fix is supposed to be a number.
    - /^v(\d+).(\d+).(\d+)$/
    # Only for development purposes
    # - feature/14-travis-new

cache:
  directories:
    - api/node_modules
    - app/webFrontend/node_modules
    - .travis/node_modules

before_script:
  # required for chrome to start properly
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # required for MongoDB to have time to start up
  - sleep 15

install:
  # install api and return back to root for following steps
  - cd api
  - npm install
  - npm prune          # remove not (anymore) in package.json required packages (to keep the cache clean)
  - cd ..
  # install frontend and return back to root for following steps
  - cd app/webFrontend
  - npm install
  - npm prune          # remove not (anymore) in package.json required packages (to keep the cache clean)
  - cd ../..
  # install travis dependencies
  - cd .travis
  - npm install
  - npm prune          # remove not (anymore) in package.json required packages (to keep the cache clean)
  - cd ..

script:
  # run license checker and write license.json / dependencies.ts
  - cd .travis
  - node license.js
  - cd ..
  # run backend-tests and return back to root for following steps
  - cd api
  - npm run test        # run backend test
  - cd ..
  # run frontend-tests and return back to root for following steps
  - cd app/webFrontend
  - npm run lint        # run linter
  # - npm run test        # run test - does not work properly
  - npm run e2e         # run end-to-end-tests
  - npm run build       # build in prod mode
  - cd ../..

after_script:
  # send required files to coveralls.io
  # - .travis/coveralls.sh

after_success:
  - .travis/package-checker.sh
  - .travis/docker.sh
  - .travis/deploy.sh
  - npm run coveralls

# Configure notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0624f63ff4c4c3705162
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   always  # options: [always|never|change] default: always
    on_cancel:  always  # options: [always|never|change] default: always
    on_error:   always  # options: [always|never|change] default: always
