# +++ TRAVIS-FILE for https://github.com/geli-lms/geli +++

# required for chrome to install
dist: trusty
# required for e2e tests to complete successfully (page crash???)
sudo: required
language: node_js
node_js:
  - "10.13"

addons:
  chrome: stable
  
services:
  - mongodb
  - docker

branches:
  only:
    - develop
    - master
    # This matches tags wit a format of v{MAJOR}.{MINOR}.{FIX} were major, minor and fix is supposed to be a number.
    - /^v(\d+).(\d+).(\d+)$/

cache:
  directories:
    - "$HOME/.npm"

stages:
  - test
  - name: deploy
    if: type = push AND (branch IN (develop, master) OR tag IS present)

jobs:
  include:
    - stage: test
      name: "Tests Api"
      install:
        - ${TRAVIS_BUILD_DIR}/.travis/changelog.sh
        - cd ${TRAVIS_BUILD_DIR}/.travis
        - npm ci
        - cd ${TRAVIS_BUILD_DIR}/api
        - npm ci
        - ${TRAVIS_BUILD_DIR}/.travis/license-crawler.sh
      script:
        - npm run lint
        - npm run test
        - npm run apidoc
      after_script:
        - cd ${TRAVIS_BUILD_DIR}
        - .travis/coveralls.sh
    - stage: test
      name: "Tests Frontend"
      before_install:
        - export NODE_OPTIONS=--max_old_space_size=4096
      install:
        - ${TRAVIS_BUILD_DIR}/.travis/changelog.sh
        - cd ${TRAVIS_BUILD_DIR}/.travis
        - npm ci
        - cd ${TRAVIS_BUILD_DIR}/api
        - npm ci
        - cd ${TRAVIS_BUILD_DIR}/app/webFrontend
        - npm ci
        - ${TRAVIS_BUILD_DIR}/.travis/license-crawler.sh
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - cd ${TRAVIS_BUILD_DIR}/api
        - npm run load:fixtures
        - npm start &
        - cd ${TRAVIS_BUILD_DIR}/app/webFrontend
        - npm run lint
        - npm run e2e
        - npm run build
    - stage: deploy
      before_install:
        - export NODE_OPTIONS=--max_old_space_size=4096
      install:
        - cd ${TRAVIS_BUILD_DIR}/.travis
        - npm ci
        - cd ${TRAVIS_BUILD_DIR}/api
        - npm ci
        - sed -i 's/$TRAVIS_COMMIT/'$TRAVIS_COMMIT'/' src/server.ts
        - cd ${TRAVIS_BUILD_DIR}/app/webFrontend
        - npm ci
        - sed -i 's/$TRAVIS_COMMIT/'$TRAVIS_COMMIT'/' src/app/shared/services/raven-error-handler.service.ts
        - ${TRAVIS_BUILD_DIR}/.travis/license-crawler.sh
      script:
        - cd ${TRAVIS_BUILD_DIR}/api
        - npm run build
        - cd ${TRAVIS_BUILD_DIR}/app/webFrontend
        - npm run build
      after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - .travis/package-checker.sh
        - .travis/apidoc.sh
        - .travis/docker.sh
        - .travis/deploy.sh
        - .travis/sentry.sh

# Configure notification
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0624f63ff4c4c3705162
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   always  # options: [always|never|change] default: always
    on_cancel:  always  # options: [always|never|change] default: always
    on_error:   always  # options: [always|never|change] default: always
