# +++ TRAVIS-FILE for https://github.com/h-da/geli +++

# required for chrome to install
dist: trusty
# required for e2e tests to complete succesfully (page crash???)
sudo: required
language: node_js
node_js:
  - "7"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      # manually update dependencies for chrome
      - libfontconfig1
      - libstdc++6
      - lsb-base
      # used for frontend e2e tests
      - google-chrome-stable

services:
  - mongodb

branches:
  only:
    - develop
    # Only for development purposes
    # - feature/14-travis-new

before_script:
  # required for chrome to start properly
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # install api and return back to root for following steps
  - cd api
  - npm install
  - cd ..
  # install frontend and return back to root for following steps
  - cd app/webFrontend
  - npm install
  - cd ../..

script:
  # run backend-tests and return back to root for following steps
  - cd api 
  # - npm run tslint      # run linter | included in command test
  - npm run test        # run backend test
  - cd ..
  # run frontend-tests and return back to root for following steps
  # npm scripts won't work here (dunno why...)
  - cd app/webFrontend
  - npm run lint        # run linter
  # - npm run test        # run test - does not work properly
  - npm run e2e         # run end-to-end-tests
  - cd ../..

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/80e48f99edac6fb0a248
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: always   # options: [always|never|change] default: always
    on_error: always    # options: [always|never|chnage] default: always
