version: "2"
services:
  db:
    image: "mongo:3.4.3"
    ports:
      - "27017:27017"
  api:
    image: "node:7.9.0"
    volumes:
      - ".:/usr/src"
    working_dir: "/usr/src/api"
    command: "npm run start"
    environment:
      - "DB_HOST=db"
    ports:
      - "3030:3030"
    links:
      - "db"
  web-frontend:
    image: "node:7.9.0"
    volumes:
      - ".:/usr/src"
    working_dir: "/usr/src/app/webFrontend"
    command: "npm run start-docker-dev"
    ports:
      - "4200:4200"
    links:
      - "api"
